/*
 * This file defines the timing model of STEP/RADAR pulses
 * generated by RP2040 PIO.
 *
 * All conversions assume:
 *  - Register-loop delay (jmp x--)
 *  - 2 PIO cycles per loop
 *
 * Changing this file changes the physical timing behavior.
 */
#include "pio_timing.hpp"
#include <limits.h>
#include <math.h>

// ===== PIO timing constants =====
// ⚠️ 这些是“硬件模型参数”，不是协议参数
constexpr float PIO_CLK_SYS = 125e6f;
constexpr float PIO_CLKDIV  = 1.0f;
constexpr float PIO_FREQ    = PIO_CLK_SYS / PIO_CLKDIV;

// STEP pulse high width in PIO loop units (625 == 10us)
constexpr uint32_t PULSE_WIDTH = 625;

uint32_t pulse_us_to_radar_len(uint32_t pulse_us)
{
    // pulse_len ≈ (pulse_us * f_pio) / (2 * 1e6)
    float len = (pulse_us * PIO_FREQ) / (2.0f * 1e6f);
    uint32_t pulse_len = (uint32_t)(len + 0.5f);

    if (pulse_len < 1) pulse_len = 1;
    return pulse_len;
}

uint32_t speed_hz_to_delay(uint32_t speed_hz)
{
    if (speed_hz == 0) {
        // delay=0 reserved as End marker
        return UINT32_MAX;
    }

    // f_step = f_pio / (7 + PULSE_WIDTH + 2 * delay)
    // => delay = 0.5 * (f_pio / f_step - (7 + PW))
    float d = 0.5f * (PIO_FREQ / (float)speed_hz
                      - (7.0f + (float)PULSE_WIDTH));

    int32_t delay = (int32_t)(d + 0.5f);
    if (delay < 1) delay = 1;

    return (uint32_t)delay;
}
